[package]
name = "semantic-release"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.15"
clap = {version = "3.2.23", default-features = false, features = ["std", "cargo"] }
regex = "1.7.0"
console = "0.15.4"
lazy_static = "1.4.0"
tempfile = "3.3.0"
