# https://numtide.github.io/devshell
imports = ["language.rust"]

[devshell]
packages = [
         "rust-analyzer",
         "gcc",
         "openssl_3.dev",
         "openssl_3",
         "pkg-config"
]

[[commands]]
package = "devshell.cli"
help = "Per project developer environments"

#[language.rust]
#packageSet =  { default = "fenix.complete.toolchain" }
#enableDefaultToolchain = false
#tools = ["rustc", "cargo", "clippy", "rustfmt", "rust-src"]

[language.rust]
enableDefaultToolchain = true
