# this should be a directory inside of the repo where the package is located
# if this isn't a monorepo you can simply put . here
# no need to put a ./ before a path, it is relative by default
subpath = "."

# tags will be built by appending the version number to whatever the tagprefix is
# if this is set to "wow-a-prefix-" (note the trailing -) and the version is "1.2.3"
# then the final tag will be "wow-a-prefix-1.2.3"
# leave this empty to have no prefix at all here
tagprefix = ""

# the files array indicates files inside of the subpath that should be handled by the tool
[[files]]
# every entry needs three components:
#
# path indicates the path to the file relative to "subpath" (but, again, without a leading ./)
path = "package.json"
# the file at "path" will be parsed into an object, the key indicates where the version string should be written to
# for a typical package.json this would be "version"
# for a Cargo.toml this would be "package.version"
key = "version"
# the type tells the tool how to parse the file.
# Currently supported values are "json" and "toml"
type = "json"

# you can specify multiple files if desired
[[files]]
path = "Cargo.toml"
key = "package.version"
type = "toml"
